//! End-to-end proof of the pairing path (Phase 18, PAIR-01/06): a code
//! generated by `famp pair invite`, redeemed by `famp pair redeem`
//! against a REAL in-process pairing router (no TLS, no child process —
//! this plan deliberately avoids both), landing on both sides'
//! `peers.keyring` as `Active` after `famp pair status` runs on the
//! inviter side.
//!
//! Two `tempfile::tempdir()` homes, literal timestamp strings, a seeded
//! `StdRng` — no test reads a wall clock except through
//! `famp_gateway::pairing_ingress::ingest_redemption`'s own internal
//! clock read (mirrors `ingress.rs`'s own external-test convention: only
//! the CRATE-INTERNAL `_at`-suffixed variant is clock-injectable, and
//! that variant is `pub(crate)`-scoped, unreachable from this external
//! test file).
//!
//! (Plan 02, 2026-08-04): the literal invite-creation timestamp was
//! bumped from `2026-08-03` to `2030-08-03` — Plan 02 wired real
//! `is_expired` enforcement into `ingest_redemption`'s real-clock read,
//! and the original literal's 24-hour window had already elapsed against
//! the real wall clock by the time Plan 02 landed, which made every test
//! here fail `expired` rather than proceed. `2030-08-03` is not a
//! magic-safe date either — it is a placeholder that will eventually need
//! the same bump — but it buys years rather than hours.

#![allow(unused_crate_dependencies)]
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::Path;
use std::sync::Arc;

use famp::cli::pair::{invite, redeem, status};
use famp::cli::peer::identity::{gateway_identity_path, gateway_peers_keyring_path};
use famp::pairing::invite::pairing_store_path;
use famp::pairing::{RedemptionReject, RedemptionRequest, Signed};
use famp::{FampSigningKey, Principal};
use famp_gateway::pairing_ingress::{build_pairing_router, ingest_redemption, PairingIngressState};
use famp_keyring::Keyring;
use rand::{rngs::StdRng, SeedableRng};
use tempfile::TempDir;

/// Write `$FAMP_HOME/own-domain` (single trimmed line) — the file-based
/// own-domain resolution tier, chosen over `FAMP_OWN_DOMAIN` env so
/// parallel tests never race a process-global env mutation
/// (`own_domain.rs`'s own documented precedence: `--domain` >
/// `FAMP_OWN_DOMAIN` env > `$FAMP_HOME/own-domain` file).
fn set_own_domain(home: &Path, domain: &str) {
    std::fs::write(home.join("own-domain"), format!("{domain}\n")).unwrap();
}

fn pairing_state_for(home: &Path, own_domain: &str) -> PairingIngressState {
    PairingIngressState::new(
        Arc::new(pairing_store_path(home)),
        Arc::new(gateway_identity_path(home)),
        Arc::from(own_domain),
    )
}

/// Build the TLS-preconfigured `reqwest::Client` the SAME way
/// `cli::pair::redeem`'s own (private) `build_client` does — this test
/// binds a plain-HTTP `127.0.0.1` loopback listener, so the client never
/// actually negotiates TLS, but constructing it via the real
/// `famp_transport_http::tls::build_client_config` path (rather than a
/// bare `reqwest::Client::new()`) matches production construction and
/// avoids a second, divergent client-build path in this test.
fn stub_client() -> reqwest::Client {
    let tls = famp_transport_http::tls::build_client_config(None).unwrap();
    reqwest::Client::builder()
        .use_preconfigured_tls(tls)
        .build()
        .unwrap()
}

/// Spawn the pairing router on an ephemeral loopback TCP port (plain
/// HTTP — this plan's test deliberately avoids TLS/child processes,
/// `run_ingress`'s TLS construction is unchanged Phase 17 code and
/// already covered by that phase's own tests). Returns the base URL and
/// a join handle the caller drops to let the server task run for the
/// lifetime of the test process (no explicit shutdown needed —
/// `#[tokio::test]` tears down its whole runtime per test).
async fn spawn_pairing_server(state: PairingIngressState) -> String {
    let router = build_pairing_router(state);
    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .expect("bind ephemeral loopback port");
    let addr = listener.local_addr().unwrap();
    tokio::spawn(async move {
        axum::serve(listener, router).await.unwrap();
    });
    format!("http://{addr}")
}

fn draw_invite(home: &Path, as_principal: &str, now: &str, seed: u64) -> String {
    let mut artifact = Vec::new();
    let mut rng = StdRng::seed_from_u64(seed);
    invite::run_at(
        home,
        &invite::PairInviteArgs {
            as_principal: as_principal.to_string(),
            url: None,
            confirm_installed: true,
        },
        &mut artifact,
        now,
        &mut rng,
    )
    .expect("invite::run_at must succeed");
    let printed = String::from_utf8(artifact).unwrap();
    printed.trim_end().lines().last().unwrap().to_string()
}

/// PAIR-01: the happy path plus the mutual-pin proof in one test — after
/// `redeem::run_at` processes the signed response AND `status::run_at`
/// processes the resulting `Redeemed` record, BOTH sides' `peers.keyring`
/// hold the other's key as `Active`. A one-directional pin is a phase
/// failure per this plan's `must_haves.truths`, not a partial success.
#[tokio::test]
async fn happy_path_pins_both_sides_mutually() {
    let inviter_home = TempDir::new().unwrap();
    let redeemer_home = TempDir::new().unwrap();
    set_own_domain(redeemer_home.path(), "redeemer.test");

    let code = draw_invite(
        inviter_home.path(),
        "agent:inviter.test/gateway",
        "2030-08-03T00:00:00Z",
        1,
    );

    let base_url =
        spawn_pairing_server(pairing_state_for(inviter_home.path(), "inviter.test")).await;

    let client = stub_client();
    let mut reader = std::io::Cursor::new(format!("{code}\n").into_bytes());
    redeem::run_at(
        redeemer_home.path(),
        &redeem::PairRedeemArgs {
            from: base_url,
            trust_cert: None,
        },
        &mut reader,
        &client,
        "2030-08-03T00:05:00Z",
    )
    .await
    .expect("redeem::run_at must succeed against a correct code");

    // Redeemer side already pinned the inviter's key as part of `redeem`.
    let inviter_principal: Principal = "agent:inviter.test/gateway".parse().unwrap();
    let redeemer_keyring =
        Keyring::load_from_file(&gateway_peers_keyring_path(redeemer_home.path())).unwrap();
    assert!(
        redeemer_keyring.get(&inviter_principal).is_some(),
        "redeemer's own keyring must hold the inviter's key as Active"
    );

    // Inviter side has NOT pinned yet — the pin only happens inside
    // `famp pair status` (PAIR-07 asymmetric completion).
    assert!(
        !gateway_peers_keyring_path(inviter_home.path()).exists(),
        "inviter side must NOT be pinned before `famp pair status` runs"
    );

    let mut status_out = Vec::new();
    status::run_at(inviter_home.path(), &mut status_out, "2030-08-03T00:10:00Z")
        .expect("status::run_at must pin the Redeemed record");

    let redeemer_principal: Principal = "agent:redeemer.test/gateway".parse().unwrap();
    let inviter_keyring =
        Keyring::load_from_file(&gateway_peers_keyring_path(inviter_home.path())).unwrap();
    assert!(
        inviter_keyring.get(&redeemer_principal).is_some(),
        "inviter's own keyring must hold the redeemer's key as Active after `pair status`"
    );

    // The record advanced Pending -> Redeemed -> Pinned.
    let store =
        famp::pairing::invite::InviteStore::load(&pairing_store_path(inviter_home.path())).unwrap();
    assert_eq!(store.invites.len(), 1);
    assert!(matches!(
        store.invites[0].state,
        famp::pairing::invite::InviteState::Pinned { .. }
    ));
}

/// A code differing by exactly one word is rejected `code_mismatch`; the
/// invite record's state stays `Pending` (T-18-03, checked-before-mutate).
///
/// (Plan 02, 2026-08-04): the store is NO LONGER byte-identical after a
/// wrong-code redemption — Plan 02 makes the attempt counter the sole,
/// deliberate mutation on this path (PAIR-02's server-side attempt
/// budget). This test now asserts the counter incremented by exactly one
/// and every other byte is unchanged, rather than full byte identity; the
/// full-byte-identity assertion moved to `pairing_ingress.rs`'s coverage
/// of the OTHER rejection paths (expired/already_redeemed/
/// attempts_exhausted/no_pending_invite), which still mutate nothing.
#[tokio::test]
async fn wrong_code_burns_one_attempt_and_stays_pending() {
    let inviter_home = TempDir::new().unwrap();
    let code = draw_invite(
        inviter_home.path(),
        "agent:inviter.test/gateway",
        "2030-08-03T00:00:00Z",
        2,
    );

    let store_path = pairing_store_path(inviter_home.path());
    let before = famp::pairing::invite::InviteStore::load(&store_path).unwrap();
    assert_eq!(before.invites[0].attempts, 0);

    // Flip exactly one word.
    let mut words: Vec<&str> = code.split(' ').collect();
    words[0] = if words[0] == "abandon" {
        "ability"
    } else {
        "abandon"
    };
    let wrong_code = words.join(" ");

    let redeemer_sk = FampSigningKey::generate();
    let redeemer_vk = redeemer_sk.verifying_key();
    let request = RedemptionRequest {
        code: wrong_code,
        principal: "agent:redeemer.test/gateway".to_string(),
        pubkey_b64url: redeemer_vk.to_b64url(),
        nonce: uuid::Uuid::now_v7().to_string(),
    };
    let signed_request = Signed::new(request, &redeemer_sk).unwrap();
    let body = serde_json::to_vec(&signed_request).unwrap();

    let state = pairing_state_for(inviter_home.path(), "inviter.test");
    let result = ingest_redemption(&body, &state).await;
    let Err(reject) = result else {
        panic!("expected a rejection for a wrong code, got {result:?}");
    };
    assert_eq!(reject.reason, "code_mismatch");

    let store = famp::pairing::invite::InviteStore::load(&store_path).unwrap();
    assert_eq!(
        store.invites[0].attempts, 1,
        "a wrong-code redemption's only mutation is the attempt counter"
    );
    assert!(matches!(
        store.invites[0].state,
        famp::pairing::invite::InviteState::Pending
    ));

    // The doc comment above claims the attempt counter is the ONLY mutation.
    // Assert exactly that, rather than trusting the two field checks above to
    // imply it: take the before-record, apply the single mutation the wrong-code
    // path is permitted to make, and require full structural equality with what
    // actually landed on disk. A stray write to `expires_at`, `code_digest`, or
    // `principal` fails here and would slip past an attempts-and-state check.
    let mut expected = before.invites[0].clone();
    expected.attempts = 1;
    assert_eq!(
        store.invites[0], expected,
        "the attempt counter must be the ONLY field a wrong-code redemption mutates"
    );
    assert_eq!(
        store.invites.len(),
        before.invites.len(),
        "a wrong-code redemption must not add or drop invite records"
    );
}

/// PAIR-06: `famp pair redeem` accepts no positional argument and no
/// code-bearing flag. `famp pair redeem hunter two three four five`
/// (5 extra positional tokens, code-shaped) must be rejected by clap
/// BEFORE any code is ever read — the only path a code enters this
/// process is the `run_at` reader parameter bound to stdin.
#[test]
fn redeem_argv_refuses_positional_code() {
    use clap::Parser;
    let result = famp::cli::Cli::try_parse_from([
        "famp", "pair", "redeem", "hunter", "two", "three", "four", "five",
    ]);
    let err = result.expect_err("a code-shaped positional argument must be rejected by clap");
    let rendered = err.to_string();
    assert!(
        rendered.contains("unexpected argument"),
        "expected clap's unexpected-argument error, got: {rendered}"
    );
}

/// T-18-07: a redeemer claiming a principal inside the INVITER's own
/// domain is refused before any store lookup.
#[tokio::test]
async fn own_domain_refused_when_redeemer_claims_inviter_authority() {
    let inviter_home = TempDir::new().unwrap();
    let code = draw_invite(
        inviter_home.path(),
        "agent:inviter.test/gateway",
        "2030-08-03T00:00:00Z",
        3,
    );

    let redeemer_sk = FampSigningKey::generate();
    let redeemer_vk = redeemer_sk.verifying_key();
    // Same domain as the inviter's own_domain below — must be refused.
    let request = RedemptionRequest {
        code,
        principal: "agent:inviter.test/impersonator".to_string(),
        pubkey_b64url: redeemer_vk.to_b64url(),
        nonce: uuid::Uuid::now_v7().to_string(),
    };
    let signed_request = Signed::new(request, &redeemer_sk).unwrap();
    let body = serde_json::to_vec(&signed_request).unwrap();

    let state = pairing_state_for(inviter_home.path(), "inviter.test");
    let result = ingest_redemption(&body, &state).await;
    let Err(RedemptionReject { reason }) = result else {
        panic!("expected own_domain_refused, got {result:?}");
    };
    assert_eq!(reason, "own_domain_refused");
}

/// The route answers `no_pending_invite` (404) whenever the invite store
/// file is absent — the unauthenticated surface is live only while an
/// invite is genuinely outstanding.
#[tokio::test]
async fn no_pending_invite_when_store_is_absent() {
    let inviter_home = TempDir::new().unwrap();
    let redeemer_sk = FampSigningKey::generate();
    let redeemer_vk = redeemer_sk.verifying_key();
    let request = RedemptionRequest {
        code: "abandon ability able about above".to_string(),
        principal: "agent:redeemer.test/gateway".to_string(),
        pubkey_b64url: redeemer_vk.to_b64url(),
        nonce: uuid::Uuid::now_v7().to_string(),
    };
    let signed_request = Signed::new(request, &redeemer_sk).unwrap();
    let body = serde_json::to_vec(&signed_request).unwrap();

    let state = pairing_state_for(inviter_home.path(), "inviter.test");
    let result = ingest_redemption(&body, &state).await;
    let Err(RedemptionReject { reason }) = result else {
        panic!("expected no_pending_invite, got {result:?}");
    };
    assert_eq!(reason, "no_pending_invite");
}
